### ISSUE TITLE
Gui-Octave problems with plotting in different formats and installing packages

### ISSUE THREAD

**Issue by dnessett** [octave-app/octave-app#33] opened 2019-04-26 21:40 UTC
## Description

Hello,

I installed gui-octave (4.4.1) on Mac OS X - High Sierra (10.13.6) from the dmg file located here: https://octave-app.org/Download.html. I am trying to save plots made with gui-octave in formats other than .ofig. I successfully did this with eps format, but all other formats generate an error, which is:

```
GenericResourceDir value does not end with directory separator.

While reading gs_res.ps:
Error: /configurationerror in GenericResourceDir
Operand stack:
   (gs_typ42.ps\000gs_cidfn.ps\000gs_cidcm.ps\000gs_fntem.ps\000gs_cidtt.ps\000gs_cidfm.ps\000gs_cmap.ps\000gs_setpd.ps\000gs_fapi.ps\000gs_typ32.ps\000gs_frsd.ps\000gs_ll3.ps\000gs_icc.ps\000gs_mex_e.ps\000gs_mro_e.ps\000gs_pdf_e.ps\000gs_wan_e.ps\000pdf...)   (gs_res.ps)   (x/y)   (/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript/Resource/x/y)
Execution stack:
   %interp_exit   --nostringval--   --nostringval--   %loop_continue   --nostringval--   --nostringval-- --nostringval--   false   1   %stopped_push   --nostringval--
Dictionary stack:
   --dict:827/1123(G)--   --dict:71/200(L)--   --dict:827/1123(G)--   --dict:175/251(G)--
Current file position is 13083
warning: broken pipe
error: gl2ps_renderer::draw: internal pipe error
error: parse error
error: called from
    __opengl_print__ at line 158 column 7
    print at line 570 column 14
```

(Note: this particular error message was for .png format).

I also thought I would install some of the packages I had installed on gui-octave 4.0.3. I began by attempting to install signal, which has a dependency on the control package.. This generated the following error:

```
>> pkg install -forge control
<built-in>: internal compiler error: Illegal instruction: 4
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [slicotlibrary.a] Error 1
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1 -Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1 -c *.f

pkg: error running `make' for the control package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 437 column 9
```

## Environment and Diagnostics

```
>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/l5/wjz73b69427bh_9x0954j0dr0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.qBCLABgpD9/Render
LC_NUMERIC=C
USER=dnessett
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.XfY6665AaK/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=107
PATH=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/janke/.rvm/bin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin
_=/usr/local/bin/env
PWD=/Users/dnessett
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//Resource/Font
LANG=en_US.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
LINES=29
XPC_SERVICE_NAME=0
HOME=/Users/dnessett
SHLVL=2
FC=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=dnessett
DISPLAY=/private/tmp/com.apple.launchd.YtFp1XrfNx/org.macosforge.xquartz:0
LC_TIME=C
ans = 0
>>
```

I don't know how to evaluate whether this problem is "weird" or not. So, I did an octave_app_diagnostic_dump in any case. Output is attached
[octave_app_diagnostic_dump.txt](https://github.com/octave-app/octave-app/files/3123078/octave_app_diagnostic_dump.txt)

**Comment by apjanke** [comment] 2019-04-26 22:07
Yep, it's "weird"! Thanks for the diagnostic dump.

Sorry you're having an issue. I will have time to look at this over the weekend.

**Comment by schoeps** [comment] 2019-04-27 13:25
I confirm the issue and the problem is located: the path layout of ghostscript under `share/ghostscript/` has changed. A quick fix is to replace the function `on export_gs_options()` in `/Applications/Octave-4.4.1.app/Contents/Resources/Scripts/main.scpt` by
```
on export_gs_options()
	return "export GS_OPTIONS=\"-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript/9.25/iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript/9.25/Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript/9.25/Resource/Font/\";"
end export_gs_options
```
@apjanke: but we may want to find an automatic way to generate this path.

**Comment by apjanke** [comment] 2019-05-04 03:32
>  but we may want to find an automatic way to generate this path.

The path is generated automatically. The problem is that for some reason, the Ghostscript version detection line is commented out. https://github.com/octave-app/octave-app-bundler/blob/7620c6c9a53ba35fcb55396c9d6c0bda7dcdd42e/bundle_octave#L395

```
  # Detect and set path for ghostscript
  gs_formula="ghostscript"
  #gs_ver="$("$install_usr/bin/gs" --version)"
  gs_opt=$("$brew" --prefix "${gs_formula}")
  gs_share="$gs_opt/share/ghostscript"
```

It looks like this is just a silly bug I introduced when working with formula versioning support. Fixed in https://github.com/octave-app/octave-app-bundler/commit/d1c04379ddbc6dbd4a1a7aee080114f2e1273721.

Surprising that none of the Octave automated tests caught this problem.

To get this fix out, I’ll need to make a new build of Octave.app 4.4.1. Let’s call it “4.4.1-u1”. And if we’re going to the trouble of doing a full new build, I think we may as well pull in a couple of the other improvements we’ve made to Octave.app since 4.4.1, like the bundled JDK.

**Comment by dnessett** [comment] 2019-05-04 05:34
Thanks for copying me on this thread. Has anyone looked at the problem I had installing packages from forge into the app? I included the information in the message in which I reported the plotting problem.
Dan
    On Friday, May 3, 2019, 8:32:37 PM PDT, Andrew Janke <notifications@github.com> wrote:  
 
 

but we may want to find an automatic way to generate this path.


The path is generated automatically. The problem is that for some reason, the Ghostscript version detection line is commented out. https://github.com/octave-app/octave-app-bundler/blob/7620c6c9a53ba35fcb55396c9d6c0bda7dcdd42e/bundle_octave#L395
  # Detect and set path for ghostscript
  gs_formula="ghostscript"
  #gs_ver="$("$install_usr/bin/gs" --version)"
  gs_opt=$("$brew" --prefix "${gs_formula}")
  gs_share="$gs_opt/share/ghostscript"

It looks like this is just a silly bug I introduced when working with formula versioning support. Fixed in octave-app/octave-app-bundler@d1c0437.

Surprising that none of the Octave automated tests caught this problem.

To get this fix out, I’ll need to make a new build of Octave.app 4.4.1. Let’s call it “4.4.1-u1”. And if we’re going to the trouble of doing a full new build, I think we may as well pull in a couple of the other improvements we’ve made to Octave.app since 4.4.1, like the bundled JDK.

**Comment by schoeps** [comment] 2019-05-04 10:32
I have no issues to compile the control pkg on my Mac (with core i7). Your error
```
>> pkg install -forge control
<built-in>: internal compiler error: Illegal instruction: 4
libbacktrace could not find executable to open
```
indicates some incompatibility with instructions set used. I though we did have overcome those problems. 

@dnessett  may I ask which mac (processor generation etc) are you using?

**Comment by dnessett** [comment] 2019-05-04 15:23
Hi,

Thanks for responding. I have a Mac Pro:

  Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	6-Core Intel Xeon
  Processor Speed:	2.66 GHz
  Number of Processors:	2

Regards,

Dan

**Comment by apjanke** [comment] 2019-05-04 17:04
> Model Identifier:	MacPro5,1

Per [Wikipedia](https://en.wikipedia.org/wiki/Mac_Pro), that's a Westmere Xeon, which is based on Nehalem. We are installing all the Homebrew formulae in "bottle" mode, which makes them build to a conservative older processor target, which is Core 2. Nehalem is a Core 2 CPU, so I think that "ought" to work.

Here's the old bug from last time we ran in to this: https://github.com/octave-app/octave-app-bundler/issues/42. In that one, it's because the `gmp` formula had a weird thing in it that was preventing it from respecting our CPU architecture setting. And:

```
[/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/gmp_6.1.2_2/6.1.2_2/lib]
$ elfx86exts libgmp.dylib
MODE64 (push)
SSE1 (xorps)
SSE2 (ucomisd)
CMOV (cmove)
BMI2 (mulx)
SSE3 (haddpd)
SSSE3 (palignr)
CPU Generation: Unknown
```

Yep, that looks like it was built for a too-new CPU architecture.

Ugh. This may be a harder fix. Customizing the `gmp` formula would require us to customize `isl`, `libmpc`, `mpfr`, `gcc`, `veclibfort`, `openblas`, `open-mpi`, `sundials@2`, and others as well.

Hmm. Maybe I could get around that by explicitly using the `--build-bottle` mechanism when we install our formulae.

**Comment by apjanke** [comment] 2019-05-04 17:15
We're in luck! Upstream Homebrew has [changed the `gmp` formula to always build for Core 2](https://github.com/Homebrew/homebrew-core/commit/9c53835ad9cd0fd99b94c20b9826bd915be87b1b), not just when building with `--build-bottle`. So I think our rebuild of 4.4.1 against our new formula arrangement (where we just use core's formulae instead of having all our own customed versioned formulae) will pick this up, and it will work.

**Comment by apjanke** [comment] 2019-05-04 17:25
The build is running now. I should have a beta of the 4.4.1 update out for you this evening.

**Comment by schoeps** [comment] 2019-05-04 17:28
yeah! Fingers crossed :)

**Comment by apjanke** [comment] 2019-05-04 20:12
Here is a beta build of Octave.app 4.4.1-u1: https://github.com/octave-app/octave-app/releases/download/v4.4.1-u1-beta1/Octave-4.4.1-u1-beta1.dmg

@dnessett: I believe this will fix both of your problems. When testing locally, saving to PNGs works. And I can see that `libgmp` no longer has the instructions for newer CPUs:

```
$ elfx86exts libgmp.dylib
MODE64 (push)
SSE1 (xorps)
SSE2 (ucomisd)
CMOV (cmove)
SSE3 (haddpd)
SSSE3 (palignr)
CPU Generation: Unknown
```

Could you download it and give it a try to see if this clears up your issues?

Test suite run looks good. If this works for dnessett, I'm going to play around with it for a day or two and then post it as the main download for Octave.app, since it fixes significant bugs. @schoeps if you have some time, could you test it, too?

**Comment by schoeps** [comment] 2019-05-04 21:50
> @schoeps if you have some time, could you test it, too?

yes, sure! I just downloaded the file and will start playing... thanks.

**Comment by apjanke** [comment] 2019-05-05 13:23
Whoops. Looks like Java's not working in this new build. I'll look in to it.

Bug for this specific issue: https://github.com/octave-app/octave-app-bundler/issues/92.

**Comment by dnessett** [comment] 2019-05-06 00:06
Sorry for the late reply. I am not receiving email notices when new comments are posted, so I didn't see this until just now when I came to the issue seeing how things were going.

Given the last contribution, should I download the beta build of Octave.app 4.4.1-u1 as requested or wait until the Java problem is fixed.

**Comment by apjanke** [comment] 2019-05-06 03:48
@dnessett Please wait until the next beta build that fixes the Java problem is out. I should have it out later tonight.

Thanks for your patience!

**Comment by apjanke** [comment] 2019-05-06 20:43
@dnessett The new beta build is out: https://github.com/octave-app/octave-app/releases/download/v4.4.1-u1-beta2/Octave-4.4.1-u1-beta2.dmg. Sorry for the delay. Please give this one a try.

**Comment by dnessett** [comment] 2019-05-06 23:34
Hi apjanke.

I was able to install the new version 4.4.1-u1-beta2 from the dmg for which you provided the link. From the new installation I was able to save plots in both png and jpg format. I was also able to install pkgs signal and optimization (in the process installing their dependent packages), but have not as yet tested them. However, I was not able to install the communications pkg. As I recall, I had difficulty installing it on 4.0.3, but can't remember how I worked around the problem to get it installed. I have attached a file of the errors generated by "pkg install -forge communications" to this message. This may be something that is fixable only by upstream developers, but I have included the errors for completeness.

Thanks,

Dan
[pkg install -forge communications fatal errors.txt](https://github.com/octave-app/octave-app/files/3150187/pkg.install.-forge.communications.fatal.errors.txt)

**Comment by apjanke** [comment] 2019-05-07 03:50
@dnessett Yay! That means it's working.

I can reproduce your problem installing the `communications` package. That looks like a separate, unrelated problem, and yeah, probably one that needs to get sent upstream to the `communications` package maintainers.

Would you mind [filing a separate issue](https://github.com/octave-app/octave-app/issues/new) for the `communications` installation failure? I'll work through it and send it upstream as needed, but our request will have more weight if it's based on a bug report from an actual user, and not one we self-reported.

**Comment by rschukey** [comment] 2019-09-08 16:59
Hello @apjanke,
thanks for addressing this bug that I had, too and it got solved now.

However I  have some questions / notes comparing the original 4.4.1.app with that of 4.4.1.u1-beta2:

1. the original 4.4.1.app is about 600 MB bigger, especially the usr/Cellar directory in original 4.4.1 app contains 91 subdirs whereas the beta2.app contains 79 subdirs. For example docbook, docbook-xsl and git are missing. I hope this doesn't matter. When starting Octave everything is fine.

2. When starting Octave I only notice that the greeting or version message prompted in the command window does not appear (like this one of original 4.4.1.app):

_GNU Octave, version 4.4.1
Copyright (C) 2018 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin15.6.0".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

Maybe exists a textfile that could be placed somewhere in the directory tree of beta2.app?

Greetings
Ralf

**Comment by apjanke** [comment] 2019-09-09 09:13
Hi @rschukey!

1. This is intentional. The original 4.4.1.app pulled in some unneeded git-related or build-time-only dependencies, and we've slimmed it down for the next release. I think all the removed apps/libraries were unneeded; please let me know if you see any actual breakage. This new build reduces the install size.

2. This is also intentional; the new 4.4.1 beta build adds the `--no-banner` or whatever option to suppress the "banner" message on startup. I prefer it this way; I think it's cleaner. All this info is available from menu options. Do you prefer seeing the banner?

**Comment by rschukey** [comment] 2019-09-09 09:24
Hi @apjanke,

thanks for your quick answer. According 2. it's ok for me if I know why I don't see the banner. So for my perspective everything is ok.

**Comment by apjanke** [comment] 2019-09-09 09:36
Great. Leaving things as is.

**Comment by apjanke** [comment] 2019-10-20 08:07
Closing as fixed; remaining problem with `communications` package will be dealt with in https://github.com/octave-app/octave-app/issues/35.

**Closed by apjanke** 2019-10-20 08:07 UTC
Labels: bug
