### ISSUE TITLE
Font management error on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by radlyeel** [octave-app/octave-app#195] opened 2020-04-15 05:42 UTC
## Description

Today I installed Octave 4.4.1 from [the download page](https://octave-app.org/Download.html) on three Macs: two Macbook Pro and one iMac.  On only one of them did it work correctly, the one that had previously had Octave 4.4.0 installed.  On the other two, which had never had Octave installed, the cursor and font behavior in the command window is borderline unusable.  The cursor is offset to the right of the actual insertion point by about 4 character widths, the characters themselves are tightly jammed, and operators such as = and - are hard to distinguish.
[octave_app_diagnostic_dump.txt](https://github.com/octave-app/octave-app/files/4479263/octave_app_diagnostic_dump.txt)

Before agreeing to run the program (which I had launched from the Applications folder by right-clicking and selecting Open, then the Open button presented by the verification process), I received this error on the two failing machines:
```
Unable to revert mtime: /Library/Fonts/
Unable to revert mtime: /Users/xxxxx/Library/Fonts
failed to write cache
```
where xxxxx is the user id used to install.

I've attached a closeup of the Command Window showing the appearance after the keystroke sequence "A=3.0".  I also have a screenshot of the editor showing a simple function; notice the parens.
<img width="144" alt="CommandWindow" src="https://user-images.githubusercontent.com/11529441/79302339-4fb42400-7ea9-11ea-9df3-588c32432f83.png">
<img width="181" alt="Editor" src="https://user-images.githubusercontent.com/11529441/79302347-53e04180-7ea9-11ea-91e0-c3b46002a344.png">

Since I have one working machine and two broken, I can do side-by-side comparisons, but I'd like some guidance on what to look for.

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/fm/dh6yxftx7fv8f9m1m00zctgr0000gn/T/
LC_NUMERIC=C
USER=daryl
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.YP4ddo13G3/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=81
PATH=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/janke/.rvm/bin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin
_=/usr/bin/env
PWD=/Users/daryl
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/Resource/Font
LANG=en_US.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
LINES=40
XPC_SERVICE_NAME=0
HOME=/Users/daryl
SHLVL=2
FC=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=daryl
LC_TIME=C
ans = 0
```

I considered installing 4.4.0, then 4.4.1, but the install guide for 4.4.0 was very strict about the Java version, and I am reluctant to go down that rat-hole (no offense intended to rats).

**Comment by apjanke** [comment] 2020-04-15 07:13
Ouch, that's no good. Sorry you're having trouble!

This is something I haven't encountered before.

That's a weird message about reverting mtime on those Fonts directories. I didn't think Octave modified those dirs, since it uses `fontcache`, which I think reads those dirs but writes its output somewhere else.

Thanks for including the diagnostic dump. Looks like you're running macOS 10.15 Catalina; I'm running 10.14 and haven't tested on 10.15 as much. Your diagnostic dump and env 
look normal to me.

> I considered installing 4.4.0, then 4.4.1, but the install guide for 4.4.0 was very strict about the Java version, and I am reluctant to go down that rat-hole (no offense intended to rats).

Actually, if you don't need to use Java code in your Octave applications (and most users don't), you can ignore that Java requirement entirely! It's only strict about the required Java version _if you want Java to work inside your Octave_. We should probably update the docs to be more clear about that.

If you want to try installing 4.4.0 first and then 4.4.1, if it's not a bother for you, could you leave one of your machines in this "broken" state while I do some research on fontcache and figure out how to diagnose this? You're the first user to report this issue, but there may well be others (maybe other 10.15 Catalina users) who encountered this and just gave up on Octave.app without reporting it, so I'd like to try to figure this out.

I wonder if maybe we're running in to some of Catalina's new system protection features?

On one of the broken machines, could you pull up the font preferences ("octave-gui" menu > Preferences, "Editor Styles" tab), see what it says for your default font, and see what it looks like when you click one of the dropdowns to display a list of fonts? It should look like this:

<img width="740" alt="Editor Styles on Octave 4 4 1 on macOS 10 14, working" src="https://user-images.githubusercontent.com/2618447/79308490-b0058e80-7ec6-11ea-9fdc-97fb61445c8c.png">

What happens when you try a couple different fonts for your Default font? In particular, try Menlo and Monaco, since those are OS-supplied fonts that should be good on any macOS install.

**Comment by apjanke** [comment] 2020-09-18 06:09
I can reproduce this issue on a macOS Catalina 10.15.6 box.

It's a freshly installed VM. When I install Octave.app 4.4.1 and run it for the first time, I get the "Plotting may be slow. Do the font cache thing?" dialog and select Yes. Then I get this error:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2618447/93561463-3b8dba80-f952-11ea-8e44-2ead230a45c3.png">

```
Unable to revert mtime: /Library/Fonts
Unable to revert mtime: /Library/Fonts
/Users/janke/Library/Fonts: failed to write cache
```

After that, Octave.app fails to launch; I'm assuming the launcher script bails out due to the `fc-cache` error.

If I re-run Octave.app again, it launches with the welcome dialog, and doesn't show the "Do the font cache thing?" dialog. (I'm guessing because the original `fc-cache` run produced at least an empty `~/.cache/fontconfig` dir. I see it exists, with a few files in it. So it looks like the cache was created, but not properly populated.)

The fonts in the Command Window and Editor are all futzed up. The Editor font especially is pretty unusable.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2618447/93562220-9b389580-f953-11ea-9e5e-134446701152.png">

Looking at Preferences shows that it's using the font "Al Bayan" for the Editor and Andale Mono for the terminal/Command Window.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2618447/93562276-b86d6400-f953-11ea-9f09-c1d888c12bca.png">

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2618447/93562293-c15e3580-f953-11ea-9cdd-c86b00290c8f.png">

Menlo is available as an option in the font dropdowns in Preferences. I tried switching to that, and it cleaned things up; code is readable now.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2618447/93562396-fa96a580-f953-11ea-856f-e94d47ef26b0.png">

@radlyeel As a workaround, could you try switching to the Menlo font for your Editor and Command Window?

**Comment by apjanke** [comment] 2020-09-18 06:21
Same issue happens with Octave.app 6.0.90 Release Candidate. This isn't specific to Octave.app 4.4.1 or 5.2.0.

**Comment by apjanke** [comment] 2020-09-18 07:20
Here's the upstream bug report: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/258

**Comment by apjanke** [comment] 2020-09-18 07:21
Well now that's weird. When I just install fontconfig via Homebrew on the same 10.15 machine and run `fc-cache` from there, I still get the "/Library/Fonts: Unable to revert mtime: /Library/Fonts" message, but it succeeds:

```
janke@catawba ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
janke@catawba ~ % fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % fc-cache -frv
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 523 fonts, 1 dirs
/System/Library/Fonts/Supplemental: caching, new cache contents: 440 fonts, 0 dirs
/Library/Fonts: Unable to revert mtime: /Library/Fonts
caching, new cache contents: 1 fonts, 0 dirs
/Users/janke/Library/Fonts: caching, new cache contents: 0 fonts, 0 dirs
/System/Library/AssetsV2/com_apple_MobileAsset_Font6: caching, new cache contents: 0 fonts, 0 dirs
/Users/janke/.local/share/fonts: skipping, no such directory
/Users/janke/.fonts: skipping, no such directory
/System/Library/Fonts/Supplemental: skipping, looped directory detected
/usr/local/var/cache/fontconfig: cleaning cache directory
/usr/local/var/cache/fontconfig: invalid cache file: 14bbaa569fa80b3226d8be152e7657ad-le64.cache-7
/Users/janke/.cache/fontconfig: not cleaning non-existent cache directory
/Users/janke/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
janke@catawba ~ % echo $?
0
janke@catawba ~ % fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % which fc-cache
/usr/local/bin/fc-cache
janke@catawba ~ % 
```

Here's the Octave.app run for comparison:

```
janke@catawba ~ % /Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % /Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache -frv     
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 523 fonts, 1 dirs
/System/Library/Fonts/Supplemental: caching, new cache contents: 440 fonts, 0 dirs
/Library/Fonts: Unable to revert mtime: /Library/Fonts
caching, new cache contents: 1 fonts, 0 dirs
/Users/janke/Library/Fonts: caching, new cache contents: 0 fonts, 0 dirs
/Users/janke/Library/Fonts: failed to write cache
/System/Library/Assets/com_apple_MobileAsset_Font5: skipping, no such directory
/Users/janke/.local/share/fonts: skipping, no such directory
/Users/janke/.fonts: skipping, no such directory
/System/Library/Fonts/Supplemental: skipping, looped directory detected
/Users/janke/.cache/fontconfig: cleaning cache directory
/Users/janke/.fontconfig: not cleaning non-existent cache directory
/Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache: failed
janke@catawba ~ % 
```

Looks to me like the only difference between the two is the "succeeded" or "failed" line at the end, and the exit status.

But... the `~/.cache/fontconfig` directory doesn't appear.

```
janke@catawba ~ % fc-cache -frv | tail -2
Unable to revert mtime: /Library/Fonts
/Users/janke/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
janke@catawba ~ % ls ~/.cache/fontconfig
ls: /Users/janke/.cache/fontconfig: No such file or directory
janke@catawba ~ % ls ~/.cache           
janke@catawba ~ %
```

I wonder where the cache is going, and why it's different for the two fontconfig installations? Is it an environment variable thing?

**Comment by apjanke** [comment] 2020-09-18 07:21
Aha! The Homebrewed one is going to `/usr/local/var/cache/fontconfig`.

The `var` for the prefix for Octave.app is actually linked to the system `/var`, because app bundles are not supposed to modify their contents, especially if they are signed (which we would like to do some day). See https://github.com/octave-app/octave-app/issues/60. Maybe we're actually running in to one of those issues now.

Think I'll report this upstream to the fontconfig folks and see what they have to say.

**Comment by apjanke** [comment] 2020-09-18 07:39
I think the fontconfig fc-cache failure might be a red herring. I got fc-cache to run so that `~/.cache/fontconfig` existed, blew away my Octave preferences (`rm -rf ~/.config/octave ~/.config/qterminal.org ~/Library/Application\ Support/Octave.app`) and re-ran Octave.app 4.4.1. No font cache dialog popped up. But the fonts were still all hosed because it was using Al Bayan and Andale Mono.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/2618447/93569457-8d890d00-f95f-11ea-9f87-b509358f5f52.png">

Maybe the issue is something simpler, like maybe macOS 10.15 Catalina no longer ships the font that Octave uses by default on Mac?

I'm not sure what the default font on Mac is supposed to be. The embedded qterminal code looks like it defaults to Monaco. But I can't reset my font adequately: on my main machine, if I blow away my Octave prefs, it still defaults to Menlo, which I'm pretty sure is a settings change I made and not Octave's actual default.

**Comment by apjanke** [comment] 2020-09-18 08:03
Oh, you know what? I fired up a fresh 10.14 Mac VM and ran Octave.app 4.4.1 there for the first time, and I got the "Unable to revert mtime" fc-cache error. But the fonts were fine. They defaulted to Monaco for both Editor and Command Window.

So I think the fontconfig fc-cache error is in fact a red herring, and it's just that Octave is picking the wrong default fonts on 10.15 for some reason.

**Comment by apjanke** [comment] 2020-09-18 13:32
Hmmm, this might already be fixed, either in newer versions of Octave or Qt. I just installed the Octave.app 6.0.90 Release Candidate (built with Qt 5.15.1) on a completely fresh macOS 10.5.6 VM, and when I fired it up, fonts looked fine, and the Editor and Command Window had both defaulted to Menlo.

Fixing this for Octave.app 4.4.x might just involve rebuilding Octave against the newer Qt. Or it might need a backport of a change in Octave to the old 4.x series. We'll see.

**Comment by stevemaser** [comment] 2021-02-17 18:25
We just ran across this bug here with Octave 6.1.0 (on 10.15 at least) -- same "mtime" error -- but it doesn't come back on the second launch of Octave.  Is this just a known issue and nothing to be concerned about?

**Comment by apjanke** [comment] 2021-02-17 20:58
> We just ran across this bug here with Octave 6.1.0 (on 10.15 at least) -- same "mtime" error 

Well, darn it. I was hoping this was fixed now.

> but it doesn't come back on the second launch of Octave. Is this just a known issue on 10.15 and nothing to be concerned about?

As long as your fonts aren't all messed up (like, Octave's GUI using wonky font choices by default like in the screenshot a few comments back), then you're fine, and it's nothing to worry about.

**Comment by stevemaser** [comment] 2021-02-17 21:26
OK -- that's what we thought.  Thanks for the confirmation!

**Comment by apjanke** [comment] 2024-07-06 10:47
Closing since this is about pretty-old versions of both Octave.app and macOS.

If this is still a problem with newer Octave.app versions (like [8.4.0](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) or [9.1.0 beta4](https://github.com/octave-app/octave-app/releases/tag/v9.1.0_beta4)) on supported versions of macOS (12 through 14), please re-open this issue and let me know what your current computer environment is.

**Closed by apjanke** 2024-07-06 10:47 UTC
Labels: bug, gui
