### ISSUE TITLE
Problem installing communications package

### ISSUE THREAD

**Issue by dnessett** [octave-app/octave-app#35] opened 2019-05-07 05:26 UTC
## Description

Attempted to install the communications package (`pkg install -forge communications`). It failed with numerous errors of the form:

```
./galois.h:24:10: fatal error: 'octave/config.h' file not found
```

Complete error output is attached to this message.

## Environment and Diagnostics

```
>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/l5/wjz73b69427bh_9x0954j0dr0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.HEL14TjRmE/Render
LC_NUMERIC=C
USER=dnessett
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.VyTZDb40RW/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=127
PATH=/Applications/Octave.app/Contents/Resources/usr/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/libexec/octave/4.0.3/site/exec/x86_64-apple-darwin14.5.0:/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/libexec/octave/api-v50+/site/exec/x86_64-apple-darwin14.5.0:/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/libexec/octave/site/exec/x86_64-apple-darwin14.5.0:/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/libexec/octave/4.0.3/exec/x86_64-apple-darwin14.5.0:/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin
_=/usr/bin/env
PWD=/Users/dnessett
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.19/iccprofiles/ -sGenericResourceDir=/Applications/Octave.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.19/Resource/ -sFontResourceDir=/Applications/Octave.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.19/Resource/Font
XPC_FLAGS=0x0
LINES=23
XPC_SERVICE_NAME=0
HOME=/Users/dnessett
SHLVL=2
GNUTERM=qt
LOGNAME=dnessett
DISPLAY=/private/tmp/com.apple.launchd.9DpXwS4UJP/org.macosforge.xquartz:0
LC_TIME=C
ans = 0
>>

```
[pkg install -forge communications fatal errors.txt](https://github.com/octave-app/octave-app/files/3150924/pkg.install.-forge.communications.fatal.errors.txt)

**Comment by apjanke** [comment] 2019-05-07 06:06
I can reproduce this in both Octave.app 4.4.1 and 5.1.0 beta 3 on macOS 10.14.4.

The crux of it looks like this:

```
>> pkg install -forge communications
In file included from galoisfield.cc:21:
./galois.h:24:10: fatal error: 'octave/config.h' file In file included from notgalois-def.cc :found21:

./galois.h:24:10: fatal error: 'octave/config.h' file not found
#include <octave/config.h>
         ^~~~~~~~~~~~~~~~~
#include <octave/config.h>
         ^~~~~~~~~~~~~~~~~
galois.cc:21:10: fatal error: 'octave/config.h' file not found
#include <octave/config.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make: *** [galois-def.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [galoisfield.o] Error 1
1 error generated.
make: *** [galois.o] Error 1
cyclgen.cc:32:17: warning: 'length' is deprecated [-Wdeprecated-declarations]
  int x_len = x.length ();
```

I ran the same `pkg install -forge communications` under a vanilla Homebrew-installed Octave 5.1.0 and a MacPorts-installed Octave 5.1.0. Same error under vanilla Homebrewed Octave. Same error when running `pkg install -forge communications` inside the MacPorts-installed Octave. However, MacPorts does provide an `octave-communications` port which correctly installs the communications package from the `sudo port` installer, even if it doesn't work from within `octave`.

Since it's broken under the other installation scenarios, too, I think this is an upstream bug, and not specific to the Octave.app packaging. I'll dig in to this a little more – especially into how `port` is able to install it under MacPorts when Octave's `pkg` is not – and then send it upstream.

This is delayed a bit because I'm currently waiting to be approved for subscription to the MacPorts `devel` mailing list. I sent a subscribe application in over the weekend but it hasn't been acted on yet.

Thank you for the report!

**Comment by zmarantz** [comment] 2019-08-23 20:09
Any updates? Still getting this error.

**Comment by apjanke** [comment] 2019-08-24 00:07
Sorry. Having health issues; haven't been able to work on Octave.app much lately. Hopefully will be able to get to this soon.

**Comment by freepcb** [comment] 2019-11-28 03:05
Just installed Octave 5.1.0 on Windows 10. Tried "pkg install -forge communications" and got:

__gfweight__.cc: In function 'octave_value_list F__gfweight__(const octave_value_list&, int)':
__gfweight__.cc:71:28: warning: 'void flush_octave_stdout()' is deprecated: [4.4]: use 'octave::flush_stdout'
instead [-Wdeprecated-declarations]
       flush_octave_stdout ();
                            ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:37:0,
                 from __gfweight__.cc:21:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\pager.h:326:1: note: declared here
 flush_octave_stdout (void)
 ^~~~~~~~~~~~~~~~~~~
cyclgen.cc: In function 'Array<int> filter_gf2(const Array<int>&, const Array<int>&, const Array<int>&, const
int&)':
cyclgen.cc:32:25: warning: 'octave_idx_type Array<T>::length() const [with T = int; octave_idx_type = long lon
g int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
   int x_len = x.length ();
                         ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclgen.cc:23:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc: In function 'Array<int> filter_gf2(const Array<int>&, const Array<int>&, const Array<int>&, const
 int&)':
cyclpoly.cc:41:25: warning: 'octave_idx_type Array<T>::length() const [with T = int; octave_idx_type = long lo
ng int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
   int x_len = x.length ();
                         ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc: In function 'octave_value_list Fcyclpoly(const octave_value_list&, int)':
cyclpoly.cc:220:55: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
             cyclic_polys.resize (cyclic_polys.length ()+1);
                                                       ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:221:47: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
             cyclic_polys(cyclic_polys.length ()-1) = (double)i;
                                               ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:236:61: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
                   cyclic_polys.resize (cyclic_polys.length ()+1);
                                                             ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:237:53: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
                   cyclic_polys(cyclic_polys.length ()-1) = (double)i;
                                                     ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:247:28: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
   if (cyclic_polys.length () == 0)
                            ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:257:46: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
           Matrix polys (cyclic_polys.length (), m+1, 0);
                                              ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
cyclpoly.cc:258:53: warning: 'octave_idx_type Array<T>::length() const [with T = double; octave_idx_type = lon
g long int]' is deprecated: [4.4]: use 'numel' instead [-Wdeprecated-declarations]
           for (int i = 0 ; i < cyclic_polys.length (); i++)
                                                     ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array-util.h:28:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MSparse.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\MatrixType.h:29,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\mx-base.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Matrix.h:31,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:30,
                 from cyclpoly.cc:24:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\Array.h:357:19: note: declared here
   octave_idx_type length (void) const { return numel (); }
                   ^~~~~~
genqamdemod.cc: In function 'octave_value_list Fgenqamdemod(const octave_value_list&, int)':
genqamdemod.cc:39:23: error: 'empty_arg' was not declared in this scope
   int arg_is_empty1 = empty_arg ("genqamdemod", nr1, nc1);
                       ^~~~~~~~~
genqamdemod.cc:39:23: note: suggested alternative: 'warn_empty_arg'
   int arg_is_empty1 = empty_arg ("genqamdemod", nr1, nc1);
                       ^~~~~~~~~
                       warn_empty_arg
genqamdemod.cc:51:29: warning: 'bool octave_value::is_real_type() const' is deprecated: [4.4]: use 'isreal' in
stead [-Wdeprecated-declarations]
   if (args(0).is_real_type () && args(1).is_real_type ())
                             ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ovl.h:36:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-fcn.h:33,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-builtin.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-int.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-dld.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:32,
                 from genqamdemod.cc:17:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov.h:708:8: note: declared here
   bool is_real_type (void) const
        ^~~~~~~~~~~~
genqamdemod.cc:51:56: warning: 'bool octave_value::is_real_type() const' is deprecated: [4.4]: use 'isreal' in
stead [-Wdeprecated-declarations]
   if (args(0).is_real_type () && args(1).is_real_type ())
                                                        ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ovl.h:36:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-fcn.h:33,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-builtin.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-int.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-dld.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:32,
                 from genqamdemod.cc:17:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov.h:708:8: note: declared here
   bool is_real_type (void) const
        ^~~~~~~~~~~~
genqamdemod.cc:73:37: warning: 'bool octave_value::is_complex_type() const' is deprecated: [4.4]: use 'iscompl
ex' instead [-Wdeprecated-declarations]
   else if (args(0).is_complex_type () || args(1).is_complex_type ())
                                     ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ovl.h:36:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-fcn.h:33,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-builtin.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-int.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-dld.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:32,
                 from genqamdemod.cc:17:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov.h:715:8: note: declared here
   bool is_complex_type (void) const
        ^~~~~~~~~~~~~~~
genqamdemod.cc:73:67: warning: 'bool octave_value::is_complex_type() const' is deprecated: [4.4]: use 'iscompl
ex' instead [-Wdeprecated-declarations]
   else if (args(0).is_complex_type () || args(1).is_complex_type ())
                                                                   ^
In file included from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ovl.h:36:0,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-fcn.h:33,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov-builtin.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-int.h:30,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\defun-dld.h:32,
                 from d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\oct.h:32,
                 from genqamdemod.cc:17:
d:\octave\octave~1.0\mingw64\include\octave-5.1.0\octave\ov.h:715:8: note: declared here
   bool is_complex_type (void) const
        ^~~~~~~~~~~~~~~
make: *** [Makefile:48: genqamdemod.oct] Error 1
make: Entering directory '/c/Users/allan/AppData/Local/Temp/oct-R1kzuS/communications-1.2.1/src'
D:/Octave/OCTAVE~1.0/mingw64/bin/mkoctfile-5.1.0.exe -DGALOIS_DISP_PRIVATES __errcore__.cc -o __errcore__.oct
D:/Octave/OCTAVE~1.0/mingw64/bin/mkoctfile-5.1.0.exe -DGALOIS_DISP_PRIVATES __gfweight__.cc -o __gfweight__.oc
t
D:/Octave/OCTAVE~1.0/mingw64/bin/mkoctfile-5.1.0.exe -DGALOIS_DISP_PRIVATES cyclgen.cc -o cyclgen.oct
D:/Octave/OCTAVE~1.0/mingw64/bin/mkoctfile-5.1.0.exe -DGALOIS_DISP_PRIVATES cyclpoly.cc -o cyclpoly.oct
D:/Octave/OCTAVE~1.0/mingw64/bin/mkoctfile-5.1.0.exe -DGALOIS_DISP_PRIVATES genqamdemod.cc -o genqamdemod.oct
make: Leaving directory '/c/Users/allan/AppData/Local/Temp/oct-R1kzuS/communications-1.2.1/src'

pkg: error running `make' for the communications package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 441 column 9

Tried the same thing on a different Windows 7 machine and got the same errors. Fortunately, the only thing I use from this package is the noise generator, so I can live without it. Everything else is working great so far.

**Comment by apjanke** [comment] 2019-11-29 11:56
@freepcb: This repo is for Octave.app, the macOS distribution of Octave. Please report issues with the Windows version to the Octave Maintainers mailing list instead: https://lists.gnu.org/mailman/listinfo/octave-maintainers.

**Comment by apjanke** [comment] 2019-12-02 23:00
Diagnostic note: `octave/config.h` is indeed missing from the installation.

```
[/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1]
$ find . -name config.h
[/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1]
$
```

**Comment by apjanke** [comment] 2024-07-06 02:46
I think this got fixed upstream at some point, probably either in Octave or the communications package. `pkg install -forge communications` now works for me in Octave.app 6.2.0, 8.4.0, 9.1.0 beta4, and 9.2.0 beta1, on various macOS environments. (Or it fails with what looks like an unrelated error on some older versions.)

Closing as Fixed/Upstream.

## Details

It's communications 1.2.6 at this point. My results from testing yesterday and today:

Apple Silicon:

* Brewed octave 9.2.0 on macOS 14 AS: ok
* Octave.app 9.2.0 beta1 on macOS 14 AS: ok
* Octave.app 9.1.0 beta4 on macOS 14 AS: ok
* Octave.app 8.4.0 on macOS 14 AS: ok
* Octave.app 6.2.0 on macOS 14 AS: Fails w/ different error
  * in ./configure stage after "checking for hdf5... no". I'm guessing bc no x64 hdf5 is available, so this fails bc 6.x and older are Intel builds.
* Octave.app 9.2.0 beta1 on macOS 12 AS: ok
* Octave.app 9.1.0 beta4 on macOS 12 AS: ok
* Octave.app 8.4.0 on macOS 12 AS: ok

Intel:

* Brewed octave 9.2.0 Intel: ok
* Octave.app 9.2.0 beta1 Intel: ok
* Octave.app 9.1.0 beta4 on Intel: ok
* Octave.app 8.4.0 on Intel: ok
* Octave.app 6.2.0 on Intel: ok
* Octave.app 4.4.1 on Intel: octapp crashes on launch
* Octave.app 4.4.1u1 on Intel: build fails in link stage with missing gfortran symbols; looks unrelated

**Closed by apjanke** 2024-07-06 02:46 UTC
Labels: bug, upstream
