### ISSUE TITLE
Mac beachball on Octave.app launch

### ISSUE THREAD

**Issue by watsodw** [octave-app/octave-app#24] opened 2019-03-13 18:04 UTC
## Description

Just after launching Octave.app the Mac spinning ball appears, Octave.app becomes unresponsive. Octave version 5.0.1 Beta 1.

## Environment

Please run `env` in Octave.app, and copy & paste the output here:

Not able to do it, but running High Sierra, 10.13.6
```
[output goes here]
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

**Comment by apjanke** [comment] 2019-03-13 18:32
Could you try doing `rm -rf ~/.config/octave` to reset your Octave settings and try launching it again?

**Comment by watsodw** [comment] 2019-03-13 18:36
Tried that, but didn't work.

**Comment by apjanke** [comment] 2019-03-13 18:47
Sounds very similar to #10.

I'm afraid there's not much I can do to diagnose it, since I can't reproduce it consistently. Maybe you can help with a diagnostic report. Could you produce a spindump capture and attach it to this bug report?

While Octave.app is hung, run Activity Monitor and locate the `octave-gui` process. (It'll probably be labeled as "Not Responding".) Click the gear button in the upper left of Activity Monitor and choose "Spindump". Once the report is produced, in the report window, click the "Save..." button in the upper right, and save it as something like "octave-5.1.0-hang-on-launch.spindump". Then compress that in a .zip file and attach it to a comment here.

**Comment by watsodw** [comment] 2019-03-13 18:52
Here it is.
[octave-5.1.0-hang-on-launch.spindump.txt.zip](https://github.com/octave-app/octave-app/files/2963119/octave-5.1.0-hang-on-launch.spindump.txt.zip)

**Comment by apjanke** [comment] 2019-03-13 18:57
Thanks! I'll see if I can make something of this.

**Comment by eflister** [comment] 2019-04-16 22:57
5.1.0beta3 hang on launch, osx 10.14.4
[Spindump - 5.1.0beta3 startup beachball.txt.zip](https://github.com/octave-app/octave-app/files/3087214/Spindump.-.5.1.0beta3.startup.beachball.txt.zip)

**Comment by apjanke** [comment] 2019-04-16 23:03
Thanks for the diagnostics! Bummer that it's still happening on the new beta 3 build. I'll have a look at that dump file too.

Also, note to self: @eflister reported the 5.1.0 beachballing upstream to Octave: https://savannah.gnu.org/bugs/index.php?56143.

**Comment by eflister** [comment] 2019-04-17 00:13
got a beachball in 4.4.1 when in debugger, made a change in the file and hit "save and run" without manually stopping debugger.

**Comment by apjanke** [comment] 2019-04-17 07:08
I edited the large spindump files down to just the Octave-related processes for easier readability:

[octave 5.1.0 hang on launch spindumps - 2019-04-16.zip](https://github.com/octave-app/octave-app/files/3088267/octave.5.1.0.hang.on.launch.spindumps.-.2019-04-16.zip)

The two spindumps here seem superficially similar. In both, the DispatchThread seems to be wedged in the keypress handler for the terminal emulation in octgui, which I believe is the Command Window. SelfListener and QFileInfoGatherer both appear to be waiting on a QMutex, and QThread is stopped in a system call inside readline getting some input for the command window. I don't know Qt programming or the Octave codebase well enough to know what that means.

```
                                                                        1000  Vt102Emulation::sendKeyEvent(QKeyEvent*) + 974 (liboctgui.5.dylib + 169502) [0x10f3ad61e]
                                                                            1000  Emulation::sendData(char const*, int) + 68 (liboctgui.5.dylib + 232264) [0x10f3bcb48]
                                                                              1000  write + 10 (libsystem_kernel.dylib + 124666) [0x7fff7c2876fa]
                                                                               *1000  hndl_unix_scall64 + 22 (kernel + 133574) [0xffffff80002209c6]
                                                                                 *1000  unix_syscall64 + 616 (kernel + 6308424) [0xffffff8000804248]
                                                                                   *1000  write_nocancel + 218 (kernel + 5536122) [0xffffff800074797a]
                                                                                     *1000  ??? (kernel + 5536522) [0xffffff8000747b0a]
                                                                                       *1000  ??? (kernel + 2884439) [0xffffff80004c0357]
                                                                                         *1000  VNOP_WRITE + 106 (kernel + 2940314) [0xffffff80004cdd9a]
                                                                                           *1000  spec_write + 748 (kernel + 2983340) [0xffffff80004d85ac]
                                                                                             *1000  ??? (kernel + 5598603) [0xffffff8000756d8b]
                                                                                               *1000  ??? (kernel + 5438214) [0xffffff800072fb06]
                                                                                                 *1000  lck_mtx_sleep + 126 (kernel + 513278) [0xffffff800027d4fe]
                                                                                                   *1000  thread_block_reason + 175 (kernel + 558655) [0xffffff800028863f]
                                                                                                     *1000  ??? (kernel + 562810) [0xffffff800028967a]
                                                                                                       *1000  machine_switch_context + 205 (kernel + 1590749) [0xffffff80003845dd]

```

I'll send the spindumps upstream to the Octave developers.

**Comment by apjanke** [comment] 2019-04-17 07:16
> got a beachball in 4.4.1 when in debugger, made a change in the file and hit "save and run" without manually stopping debugger.

That does tend to happen, I'm afraid, even in 4.4.1. That particular case probably deserves a separate upstream bug report (because of its reproducibility and specific circumstances); I just haven't gotten around to posting it yet.

**Comment by apjanke** [comment] 2019-04-17 07:46
> got a beachball in 4.4.1 when in debugger, made a change in the file and hit "save and run" without manually stopping debugger.

Looks like this is actually fixed in 5.1.0. I can no longer reproduce it there.

**Comment by apjanke** [comment] 2019-04-17 10:03
Got a beachball on startup myself, using a brewed Octave 5.1.0 instead of Octave.app.

[octave 5.1.0 beachball on startup - brewed - apjanke - spindump.txt.zip](https://github.com/octave-app/octave-app/files/3088998/octave.5.1.0.beachball.on.startup.-.brewed.-.apjanke.-.spindump.txt.zip)

I think we can probably say this is an upstream issue, and not particular to Octave.app's packaging. Tagging as "upstream".

**Comment by apjanke** [comment] 2019-04-17 10:16
> Please run env in Octave.app, and copy & paste the output here:
>
> Not able to do it, but running High Sierra, 10.13.6

Oops! I meant `system env`. I have corrected the issue template.

**Comment by apjanke** [comment] 2024-01-14 12:36
Closing as stale issue: no recent activity, I can't reproduce, and we're moving on to Octave 8.x now; hopefully that'll fix this.

**Closed by apjanke** 2024-01-14 12:36 UTC
Labels: bug, upstream
