### ISSUE TITLE
Fail to install package control on Mac 10.15.6

### ISSUE THREAD

**Issue by higherkuo** [octave-app/octave-app#210] opened 2020-10-07 00:30 UTC
Hi,

I was trying to install package for octave on my Mac, but I always get the same error message. I tried home-brew, or octave-app, and even octave 4.4.1. This makes me wonder the error is on my environment. The error message is following:

Any suggestions? Thanks!

```
octave:1> pkg install -f control
error: pkg: failed to read package '-f': Couldn't resolve host name
error: called from
    pkg at line 433 column 17
octave:1> pkg install -forge control
configure: error: in `/var/folders/2p/zk_34fj93l9fqh9ccx5661xc0000gq/T/oct-IR9Vfw/control-3.2.0/src':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
checking for mkoctfile... /usr/local/Cellar/octave/5.2.0_10/bin/mkoctfile-5.2.0
checking for octave-config... /usr/local/Cellar/octave/5.2.0_10/bin/octave-config-5.2.0
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling...
pkg: error running the configure script for control.
error: called from
    configure_make at line 82 column 9
    install at line 190 column 7
    pkg at line 441 column 9
octave:1>
```

**Comment by apjanke** [comment] 2020-10-09 15:58
This line:

```
configure: error: in /var/folders/2p/zk_34fj93l9fqh9ccx5661xc0000gq/T/oct-IR9Vfw/control-3.2.0/src': configure: error: cannot run C++ compiled programs. If you meant to cross compile, use --host'.
```

makes me suspect your environment. That's a pretty basic error. And I couldn't reproduce your error on my systems.

A couple things to check:
* Have you run Xcode once and accepted the license agreement?
* Can you build other basic C or C++ programs outside the Octave environment, for example with Homebrew?

**Comment by apjanke** [comment] 2024-07-04 13:17
Closing this ticket as no-recent-response / can't-reproduce / think-it's-fixed.

**Closed by apjanke** 2024-07-04 13:17 UTC
Labels: bug
