### ISSUE TITLE
image package Installing error

### ISSUE THREAD

**Issue by Salmansabir3** [octave-app/octave-app#13] opened 2018-12-29 03:55 UTC
Hey guys! I am unable to install any package (or specifically image package) in octave. While installing image package I encountered the following error:

>> pkg install -forge image
sh: 1: make: not found

pkg: error running `make' for the image package.
error: called from
    configure_make at line 95 column 9
    install at line 194 column 7
    pkg at line 394 column 9

**Comment by apjanke** [comment] 2019-01-02 17:59
Okay. Download this `octave_app_diagnostic_dump.m` file: https://github.com/octave-app/octave-app-bundler/blob/master/Mcode/octave_app_diagnostic_dump.m, run it, and attach the output file to this bug report. Hopefully that will give us some leads.

**Comment by apjanke** [comment] 2019-01-03 00:13
FYI, I tried to reproduce this by making a brand new OS X 10.11 VM, installing Octave.app 4.4.0 on it, and running `pkg install -forge image`. It produced the usual error that happens when you haven't installed Xcode:

```
>> pkg install -forge image
configure: error: in `/var/folders/jx/n24ps_yj5sn6hmc0vs_51tc00000gn/T/oct-JNnxbF/image-2.10.0/src':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
checking for a sed that does not truncate output... /Applications/Octave-4.4.0.app/Contents/Resources/usr/bin//gsed
checking for octave... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/octave-4.4.0
checking for mkoctfile... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/mkoctfile-4.4.0
checking whether the C++ compiler works... no

pkg: error running the configure script for image.
error: called from
    configure_make at line 78 column 9
    install at line 184 column 7
    pkg at line 437 column 9
```

After choosing to "Install" the command line tools from the prompt that popped up, I ran it again, and it succeeded.

Never encountered an error about `make` not existing. And `/usr/bin/make` was there at the initial OS installation.

Maybe this is a local machine configuration issue? The output from that diagnostic script might help figure it out.

**Comment by apjanke** [comment] 2019-12-02 22:55
I still can't reproduce. Closing as "worksforme".

**Closed by apjanke** 2019-12-02 22:55 UTC
Labels: bug, worksforme

**Comment by hoo2** [comment] 2020-03-14 13:18
I just installed octave(5.2.0) from brand new ubuntu 19.10 via snap and I have the same behaviour.
