### ISSUE TITLE
'configure_make' error when trying to install a package from Octave Forge

### ISSUE THREAD

**Issue by agathauy** [octave-app/octave-app#5] opened 2018-09-14 14:15 UTC
Hi, I tried different variations of Octave 4.4, this one and the one from Homebrew (they might be the same), the command line version and the gui version, and I get the same error every time.

As a sanity check of whether my gcc build has a problem, I tried using Octave 4.0.3 again, and I can install packages there. But not the packages with a requirement of >=4.2.0.

I've also tried uninstalling the one from Homebrew, and just have these 4.0.3 and 4.4.0 versions that are in ".app" form.

Here is the error code that appears for example when I install "io":
```
>> pkg install -forge io
dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
./config.status: line 761: 71892 Abort trap: 6           $AWK -f "$ac_tmp/defines.awk" 'config.h.in'
config.status: error: could not create config.h
checking for mkoctfile... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/mkoctfile-4.4.0
checking for octave-config... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/octave-config-4.4.0
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... clang++ -std=gnu++11 -E
checking   is_numeric_type or isnumeric... isnumeric
checking   is_cell or iscell... iscell
checking   is_empty or isempty... isempty
configure: creating ./config.status
config.status: creating config.h

pkg: error running the configure script for io.
error: called from
    configure_make at line 78 column 9
    install at line 184 column 7
    pkg at line 437 column 9
```

**Comment by apjanke** [comment] 2018-09-17 03:12
> dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
>  Referenced from: /usr/local/bin/awk
>  Reason: image not found

This looks like your Homebrew installation may have a broken gawk installation due to a dylib version change in its mpfr dependency. That is, your gawk was built against an older version of mpfr that provided libmpfr.4.dylib; the current mpfr provides libmpfr.6.dylib.

(I assume you are using gawk and not awk here, because plain awk does not link to mpfr, as far as I can tell.)

Try doing the following to fix it up:

brew update
brew upgrade
brew reinstall gawk

**Comment by agathauy** [comment] 2018-09-17 04:13
@apjanke Omg thank you for spotting that! I've googled for hours on this and the consensus by people was there was a bug for Octave 4.4.0 with Mac OS X. Such that I installed Octave on Bootcamp instead. Thank you for the help! It works now :D 

Actually, I didn't notice it because I'm not familiar with gawk or awk so I know I didn't manually install that. I should read up on it.

**Comment by apjanke** [comment] 2018-10-16 06:39
It looks to me like this error is not specific to Octave.app.

I was able to reproduce that same compilation error when doing `pkg install -forge linear-algebra`. However, it also happens when run from the plain Homebrew-installed Octave. So it looks like this is an issue in either the `linear-algebra` Octave-Forge package, or in Octave's own `mkoctfile`.

Please report this issue upstream to the [Octave-Help mailing list](https://lists.gnu.org/mailman/listinfo/help-octave). Both the core Octave and Octave-Forge maintainers read that list, and should be able to help you with this issue.

Closing as an upstream issue.

**Closed by apjanke** 2018-10-16 06:39 UTC
