### ISSUE TITLE
Octave 5.2 Crashes on call to plot()

### ISSUE THREAD

**Issue by sparkie3** [octave-app/octave-app#194] opened 2020-04-14 16:02 UTC
## Description

Replace this section with a description of the problem, including:
  * What you did: tried to call plot(x,y)
  * What you expected to happen: a plot to be drawn
  * What actually happened: Octave crashes and closes
As an aside, I'm just not familiar with how to troubleshoot such an issue. I know that 4.2 from the repos had no issues with plotting.

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
>> libpng error: profile 'sRGB IEC61966-2.1': D0F7D4FBh: length does not match profile
>> system 'env'
SHELL=/bin/sh
WINDOWID=79691783
KDED_STARTED_BY_KDEINIT=1
QT_SCREEN_SCALE_FACTORS=eDP-1-1=1;HDMI-1-1=1;
COLORTERM=truecolor
XDG_CONFIG_DIRS=/app/etc/xdg:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
LANGUAGE=
SSH_AUTH_SOCK=/tmp/ssh-YbrCQhs4bJJV/agent.3453
XDG_DATA_HOME=/home/sparkie/.var/app/org.octave.Octave/data
SHELL_SESSION_ID=2d1b15b6149a45958545af02179b2942
XDG_CONFIG_HOME=/home/sparkie/.var/app/org.octave.Octave/config
DESKTOP_SESSION=plasma
SSH_AGENT_PID=3510
FLATPAK_ID=org.octave.Octave
KDE_FORK_SLAVES=1
XDG_SEAT=seat0
PWD=/home/sparkie
XDG_SESSION_DESKTOP=KDE
LOGNAME=sparkie
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
_=/usr/bin/env
XAUTHORITY=/run/user/1000/Xauthority
LINES=49
GI_TYPELIB_PATH=/app/lib/girepository-1.0
LDFLAGS=-L/app/lib
HOME=/home/sparkie
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=KDE
KICAD_PATH=/usr/share/kicad
KONSOLE_DBUS_SERVICE=:1.1433
COLUMNS=115
KONSOLE_DBUS_SESSION=/Sessions/1
PROFILEHOME=
AT_SPI_BUS_ADDRESS=unix:path=/run/user/1000/at-spi-bus
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
CPPFLAGS=-I/app/include
PULSE_CLIENTCONFIG=/run/user/1000/pulse/config
KONSOLE_VERSION=191203
KDE_SESSION_UID=1000
XDG_CACHE_HOME=/home/sparkie/.var/app/org.octave.Octave/cache
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm
KIGITHUB=https://github.com/KiCad
LESSOPEN=| /usr/bin/lesspipe %s
LIBVIRT_DEFAULT_URI=qemu:///system
USER=sparkie
COLORFGBG=0;15
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
DISPLAY=:99.0
SHLVL=2
FLATPAK_SANDBOX_DIR=/home/sparkie/.var/app/org.octave.Octave/sandbox
XDG_VTNR=1
XDG_SESSION_ID=3
GST_PLUGIN_PATH=/app/lib/gstreamer-1.0:/app/lib/x86_64-linux-gnu/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/extensions/gstreamer-1.0
QML2_IMPORT_PATH=/app/lib64/qml:/app/lib/qml
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=C
QT_AUTO_SCREEN_SCALE_FACTOR=0
XCURSOR_THEME=breeze_cursors
XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/share
KDE_FULL_SESSION=true
PATH=/app/bin:/usr/bin:/app/jre/bin:/app/libexec/octave/5.2.0/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/api-v53/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/5.2.0/exec/x86_64-pc-linux-gnu:/app/bin
OCTAVE_HOME=/app
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
QT_PLUGIN_PATH=/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins
PULSE_SERVER=unix:/run/user/1000/pulse/native
LC_NUMERIC=C
KONSOLE_DBUS_WINDOW=/Windows/1
ans = 0
>>
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by apjanke** [comment] 2024-07-06 09:51
This looks like it's an installation of regular GNU Octave on Linux, not an installation of Octave.app. This [octave-app repo](https://github.com/octave-app/octave-app) is specifically for [Octave.app](https://octave-app.org/), which is a special "native Mac app" distribution of GNU Octave.

For problems with regular Octave, head over to the Octave Discourse at https://octave.discourse.group/, or their Savannah bug tracker at https://savannah.gnu.org/projects/octave.

Closing as not Octave.app-specific.

> What you did: tried to call plot(x,y)
> [...]
>
>  I'm just not familiar with how to troubleshoot such an issue. I know that 4.2 from the repos had no issues with plotting

Best way is to include a "MSCRE" - Minimal Self-Contained Reproducible Example - that's a little script that can be run in the program with no additional setup, and will reproduce your problem. For example, if I fire up a fresh Octave session and just run `plot(x,y)`, it raises an error complaining that x is undefined.

```
>> plot(x,y)
error: 'x' undefined near line 1, column 6
>>
```

You need to say how t set up `x` in order to provide an example that makes it easy for developers to reproduce your problem. Easiest way is to write that in to a little script, and include the whole script in your bug report.

**Closed by apjanke** 2024-07-06 09:51 UTC
