### ISSUE TITLE
octave-cli shows no available graphics toolkits

### ISSUE THREAD

**Issue by mpiqueca** [octave-app/octave-app#206] opened 2020-09-17 16:50 UTC
Started /Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90 in Terminal window
Attempt to run 'sombrero' returns 'error: no graphics toolkits are available!'
Running 'available_graphics_toolkits()' returns 'ans = {}(1x0)'
Running inside Command Window in the gui version returns 'qt' and all graphics demos appear to work.
Running from Terminal /Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-6.0.90 --no-gui shows 'qt' available and graphics appears to work.

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/_l/_w9ms9sd10936lk6dpx2srhw0000gp/T/
TERM_PROGRAM_VERSION=438
LC_NUMERIC=C
TERM_SESSION_ID=BFE22BCF-CA4B-4605-B2E8-BBE244CF9763
CDPATH=.:~:~/Documents:~/Documents/dxms
USER=mp
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.xbRm2Uqn1W/Listeners
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
COLUMNS=80
PATH=/opt/local/bin:/opt/local/sbin:.:/Users/mp/bin/share:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mp/bin/share:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/6.0.90/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/api-v55/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/6.0.90/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin
_=/usr/bin/env
LaunchInstanceID=FD464AAF-5CB1-4E9E-98D7-66E294D09323
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/mp
LANG=en_US.UTF-8
XPC_FLAGS=0x0
LINES=24
XPC_SERVICE_NAME=0
HOME=/Users/mp
SHLVL=2
LOGNAME=mp
SECURITYSESSIONID=186a4
LC_TIME=C
ans = 0
```

**Comment by apjanke** [comment] 2020-09-18 02:56
Hmm. I'm getting slightly different behavior on my macOS 10.14 box.

```
[~] $ /Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90 -q
octave:1> available_graphics_toolkits
ans =
{
  [1,1] = gnuplot
}

octave:2> sombrero

gnuplot> set terminal aqua enhanced title "Figure 1" size 560 420  font "*,6.66667" dashlength 1
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
octave:3> exit
[~] $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G6020
[~] $
```

I'm pretty sure that:
1. You should have gnuplot available in that graphics toolkit list, and
2. We need to do something to fix gnuplot and how it doesn't like the "aqua" terminal here

I think it is expected that the `qt` toolkit is not available in the `octave-cli` build; that is explicitly not running with Qt.

Looks like this is not a new issue with the 6.x build, at least not for the gnuplot aqua not working; I get the same behavior in Octave.app 5.2.0 and 4.4.1:

```
[~] $ /Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app\@5.2.0/5.2.0/bin/octave-cli-5.2.0 -q
octave:1> available_graphics_toolkits
ans =
{
  [1,1] = gnuplot
}

octave:2> sombrero

gnuplot> set terminal aqua enhanced title "Figure 1" size 560 420  font "*,6.66667" dashlength 1
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
octave:3> exit
[~] $ /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app\@4.4.1/4.4.1/bin/octave-cli -q
octave:1> available_graphics_toolkits
ans =
{
  [1,1] = gnuplot
}

octave:2> sombrero

gnuplot> set terminal aqua enhanced title "Figure 1" size 560 420  font "*,6.66667" dashlength 1
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
octave:3>
```

Could you run `octave_app_diagnostic_dump` in your Octave.app octave-cli session and attach its output file to this issue?

**Comment by apjanke** [comment] 2020-09-18 03:01
Aha, here's a clue: it looks like Octave.app might be pulling in the `gnuplot` command from my Homebrew installation on my box, and not the gnuplot that's included with Octave.app itself.

```
[~] $ /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app\@4.4.1/4.4.1/bin/octave-cli -q
octave:1> sombrero

gnuplot> set terminal aqua enhanced title "Figure 1" size 560 420  font "*,6.66667" dashlength 1
                      ^
         line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
octave:2> system('which gnuplot')
/usr/local/bin/gnuplot
ans = 0
octave:3> getenv('PATH')
ans = /usr/local/sbin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/Users/janke/bin:/usr/local/bin:/usr/local/sbin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/Users/janke/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/janke/local/go-work/bin:/Users/janke/.rvm/bin:/Users/janke/local/go-work/bin:/Users/janke/.rvm/bin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin
octave:4>
```

I will bet that's because of this:

```
[Octave-4.4.1.app] $ find . -name gnuplot
./Contents/Resources/usr/Cellar/gnuplot-octave-app/5.2.8/bin/gnuplot
./Contents/Resources/usr/Cellar/gnuplot-octave-app/5.2.8/libexec/gnuplot
./Contents/Resources/usr/Cellar/gnuplot-octave-app/5.2.8/share/gnuplot
[Octave-4.4.1.app] $ ls Contents/Resources/usr/Cellar/bin/gnuplot
gls: cannot access 'Contents/Resources/usr/Cellar/bin/gnuplot': No such file or directory
[Octave-4.4.1.app] $
```

There's no `gnuplot` link in the main `bin` directory in Octave.app.

And _that's_ because Octave.app uses a special `gnuplot-octave-app` Formula/build that is linked to our hacked `qt-octave-app` formula. And `gnuplot-octave-app` is keg-only, so it doesn't get linked!

I think what needs to happen here is that the environment setup in our launcher script needs to get the `gnuplot-octave-app` cellar or opt location in to the `$PATH`.

But that won't help when running `octave-cli` from the command line, because that bypasses our launcher script. Hmmm. I'm not sure what the right way to make command-line Octave.app `octave` invocations aware of our keg-only dependencies is.

**Comment by apjanke** [comment] 2020-09-18 03:03
I think that once we're running the right gnuplot, the "aqua" problem can be fixed by changing `gnuplot-octave-app` to build `--with-aquaterm` by default. I'll give that a try.

**Comment by apjanke** [comment] 2020-09-18 03:07
The way we handle this with the Octave.app GUI is by having it tell gnuplot to use the Qt terminal by default, by [setting `GNUTERM=qt` before launching octave](https://github.com/octave-app/octave-app-bundler/blob/52fc047be02c3fb6841856a8821cb3cf82b3c537/bundle_octave#L479-L481).

As a workaround, could you try running `export GNUTERM=qt` before running `octave-cli`?

```
[~] $ export GNUTERM=qt
[~] $ /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app\@4.4.1/4.4.1/bin/octave-cli -q
octave:1> sombrero
qt.qpa.fonts: Populating font family aliases took 713 ms. Replace uses of missing font family "Sans" with one that exists to avoid this cost.
octave:2>
```

**Comment by apjanke** [comment] 2020-09-18 03:28
Oh. LOL. Here's the aquaterm problem: AquaTerm [is a separate program](https://sourceforge.net/projects/aquaterm/), and it installs as a native Mac app bundle or cask, not a vanilla Unix program, so you can't pull it in with a Homebrew formula. It might be difficult to distributed that with Octave.app. I'm going to make the AquaTerm thing a low priority, and focus on getting gnuplot working with the Qt terminal here.

**Comment by apjanke** [comment] 2020-09-18 03:39
Here's a writeup of what I think the underlying cause is here: https://github.com/octave-app/octave-app/issues/207

**Comment by apjanke** [comment] 2020-09-18 03:58
Ah: AquaTerm is distributed as a custom `.pkg` installer and not a plain application bundle. That is definitely a WONTFIX for us.

Focusing on getting gnuplot working with Qt.

**Comment by mpiqueca** [comment] 2020-09-18 16:45
I may be too late - thanks for your new overnight research

Trying each of these three in order didn't change the CLI "no available graphics toolkits"
1. env GNUTERM=qt /Applications/Octave-6.0.90.app//Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90

2. export GNUTERM=qt
   /Applications/Octave-6.0.90.app//Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90

3. added 'export GNUTERM=qt' to both ~/.bash_login and ~/.bashrc
  /Applications/Octave-6.0.90.app//Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90

Diagnostic dump attached:
[octave_app_diagnostic_dump.txt](https://github.com/octave-app/octave-app/files/5246882/octave_app_diagnostic_dump.txt)

**Comment by apjanke** [comment] 2020-09-18 16:51
That is actually expected, I think: the `GNUTERM` variable doesn't affect what graphics toolkits that Octave uses, rather it controls what terminal type gnuplot uses once Octave is using the gnuplot toolkit; the problem of getting Octave to recognize gnuplot properly happens before `$GNUTERM` comes in to play. So it won't be enough on its own.

Could you try:
```
export GNUTERM=qt
PATH="/Applications/Octave-6.0.90.app//Contents/Resources/usr/gnuplot-octave-app/bin:$PATH"
```

And then run `/Applications/Octave-6.0.90.app//Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90` and see what happens? I *think* that'll make the `gnuplot` graphics toolkit available to you.

And if you want a slightly shorter way of calling it, `/Applications/Octave-6.0.90.app/Contents/Resources/usr/opt/octave-octave-app@6.0.90/bin/octave-cli` should be equivalent.

**Comment by mpiqueca** [comment] 2020-09-18 20:09
That just about worked!  My installation has a slightly different PATH to ..../bin/gnuplot, but this works 👍 :

alias oct60cli='env PATH=/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/gnuplot-octave-app/5.4.0/bin:$PATH GNUTERM=qt /Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin/octave-cli-6.0.90'

(I prefer the "env" so the alias doesn't keep making my main shell path longer and longer)

I still get the 'slow font initialization' but I know you have that in progress.  

Thanks and this is really helpful so I can try my octave-running shell scripts. I often have a wrapper "#! /usr/local/bin/octave -qf" script that handles Shell command line args and invokes a ".m" file.  I just have to keep /usr/local/bin/octave symlinked to the right place.

**Comment by apjanke** [comment] 2020-09-18 21:09
Excellent. My co-maintainer Sebastian has weighed in and thinks setting up wrapper scripts that are callable from the command line is a good idea, so I'm going to proceed with working on that. Should have a more convenient solution for you some time soon.

> My installation has a slightly different PATH to ..../bin/gnuplot

Your path is the right one; I typoed in my example.

**Comment by apjanke** [comment] 2024-07-04 13:26
So, I think I may have misunderstood this whole issue.

I think the `octave-...` command with the `-cli` infix there is an intentional no-GUI/no-graphics variant, for use in headless/text-only environments. If you want a terminal-mode octave session that doesn't run the whole Desktop GUI think but can still do plots, call `octave` or `octave-X.Y.Z` without the `-cli-` part in it, _and_ omit the `--gui` option.

So I think this is actually working as intended. And I think the gnuplot-specific stuff is a red herring. (Or, maybe the "-cli-" variant is the no-Qt version but "-cli-" still supports gnuplot. But as of 8.x, Octave.app has dropped gnuplot, because it's finicky, and kinda abandonware at this point. Sorry if you were actually using that.)

If I misunderstood that, please re-open this issue?

**Closed by apjanke** 2024-07-04 13:26 UTC
Labels: bug
