### ISSUE TITLE
Full screen mode problems

### ISSUE THREAD

**Issue by shlyakpavel** [octave-app/octave-app#18] opened 2019-01-11 08:20 UTC
## Description

What I did was:
```
x = linspace(0.1,60,1000);
y = 2.^(-0.2*x+10);
subplot (2, 2, 1)
plot(x, y);
subplot (2, 2, 2)
semilogy(x,y);
subplot (2, 2, 3)
semilogx(x,y);
subplot (2, 2, 4)
loglog(x,y);
```
In full screen mode
I got:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19782228/51021510-cbcb0800-1592-11e9-872a-de85bdceff74.png">

What I expected it to look like:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19782228/51021534-e1d8c880-1592-11e9-9220-6288e34a525c.png">

## Environment

<img width="299" alt="image" src="https://user-images.githubusercontent.com/19782228/51021454-9faf8700-1592-11e9-9b8f-deb12250de7d.png">

**Comment by apjanke** [comment] 2019-01-11 08:36
What's the output of `ver` in your Octave?

**Comment by shlyakpavel** [comment] 2019-01-11 08:39
```
>> ver
----------------------------------------------------------------------
GNU Octave Version: 4.4.1 (hg id: 1f46d371968c)
GNU Octave License: GNU General Public License
Operating System: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
----------------------------------------------------------------------
Package Name  | Version | Installation directory
--------------+---------+-----------------------
       image  |  2.10.0 | /Users/pavel/Library/Application Support/Octave.app/4.4.1/pkg/image-2.10.0
```

**Comment by apjanke** [comment] 2019-01-11 09:42
I can reproduce with Octave.app 4.4.0 and 4.4.1-beta3.

I can also reproduce with a vanilla Homebrewed `brew install octave --with-qt`.

It looks like this is an upstream Octave problem, not a problem with the Octave.app packaging. Please report this upstream to GNU Octave at https://savannah.gnu.org/bugs/?func=additem&group=octave.

Closing as upstream.

**Closed by apjanke** 2019-01-11 09:42 UTC
Labels: bug
