### ISSUE TITLE
Octave outputs error logs on Apple silicon Mac

### ISSUE THREAD

**Issue by y-vectorfield** [octave-app/octave-app#296] opened 2024-10-07 01:48 UTC
## Description

I installed Octave App on my Apple silicon Mac using Homebrew.
However, this outputs unexpected error logs like the following texts.

FALLBACK (log once): Fallback to SW vertex for line stipple
FALLBACK (log once): Fallback to SW vertex processing, m_disable_code: 2000
FALLBACK (log once): Fallback to SW vertex processing in drawCore, m_disable_code: 2000

This bug was previously considered fixed; however, it has reoccurred.

I use Octave 9.2.0 App on macOS 14.7 Sonoma. My Mac machine is equipped with an M1 Pro processor.

```
I executed the following codes.

graphics_toolkit('qt')
x=-2*pi:0.1:2*pi;
y=sin(x);
plot(x, y);
```

This issue also occurred on CLI version of this.

https://savannah.gnu.org/bugs/index.php?66274

## Environment and Diagnostics
Octave 9.2.0
macOS 144.7 Sonoma & 15.0.1 Sequoia

Please run `system env` in Octave.app, and copy & paste the output here:

```
FALLBACK (log once): Fallback to SW vertex for line stipple
FALLBACK (log once): Fallback to SW vertex processing, m_disable_code: 2000
FALLBACK (log once): Fallback to SW vertex processing in drawCore, m_disable_code: 2000
```

**Comment by unfixa1** [comment] 2024-10-09 04:12
Make sure you are using the latest version of Octave and related graphics libraries. You can update via Homebrew:
brew update
brew upgrade octave
Also, you can use [servbay](servbay.com) to check environment compatibility issues and eliminate environment bugs, which is more suitable for Mac than homebrew

**Comment by apjanke** [comment] 2024-10-13 07:30
Hi, @y-vectorfield. I don't know if you're actually running Octave.app here, as opposed to regular Octave. Octave.app is a special "native Mac app" distribution of Octave, available from https://octave-app.org/.

Regardless, this looks like an upstream issue with Octave itself, not something caused by Octave.app's packaging. Pursuing this with the [upstream Savannah ticket 66274 you posted](https://savannah.gnu.org/bugs/index.php?66274) is probably the best approach. That Savannah bug tracker is the one for Octave itself.

Closing this ticket as upstream issue.

> Also, you can use [servbay](https://github.com/octave-app/octave-app/issues/servbay.com) to check environment compatibility issues and eliminate environment bugs, which is more suitable for Mac than homebrew

This is nonsense. ServBay doesn't handle Octave or its dependencies, and is not suitable for use here. Please do not post ads on my bug tracker, @unfixa1.

**Closed as completed by apjanke** 2024-10-13 07:30 UTC
Labels: upstream
